export const SET_PRODUCTS_LIST = 'SET_PRODUCTS_LIST';
export const PRODUCTS_LIST_LOADING = 'PRODUCTS_LIST_LOADING';
export const PRODUCTS_LIST_ERROR = 'PRODUCTS_LIST_ERROR';
export const SET_SELECTED_PRODUCT = 'SET_SELECTED_PRODUCT';
